### ISSUE TITLE
Change Assembly/Disassembly Format + Highlighting

### ISSUE THREAD

**Issue by Cryptogenic** [Cryptogenic/REBot#4]
Fix the format so that instructions come before opcodes, and opcodes are commented out. Additionally, add syntax highlighting via `x86asm` highlight markdown tag.

Finally, make padding relative to the longest instruction, and add offsets to the comments.

Example:
```x86asm
jmp rdi ; +0 = ff e7
ret     ; +2 = c3
nop     ; +3 = 90
```

**Comment by bivhitscar** [comment]
Sorry, I didn't think to ask if you'd started on this before diving in. Hopefully my changes are alright.

**Comment by Cryptogenic** [comment]
Thanks :D Code reviewed and looks good, merging.
